export const API_URL = 'http://localhost:5000';

export const LOCAL_STORAGE_KEY = 'THEME';

export const COLORS = {
	LIGHT_THEME_BACKGROUND_COLOR: '#FFF',
	DARK_THEME_BACKGROUND_COLOR: '#1e2227',
	LIGHT_THEME_TEXT_COLOR: '#717180',
	DARK_THEME_TEXT_COLOR: '#FAFAFA',
	LIGHT_THEME_HEADER_COLOR: '#fff',
	DARK_THEME_HEADER_COLOR: '#212121',
};